apiVersion: apps/v1
kind: Deployment
metadata:
  name: roseaw-nginx-deployment
spec:
  replicas: 1  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cithit/roseaw-nginx:latest
        ports:
        - containerPort: 80  # Expose NGINX on port 80        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000
